export const courseData = {
  "class-11-commerce": {
    id: "class-11-commerce",
    title: "Class 11 Commerce",
    description:
      "Comprehensive commerce education for Class 11 students with expert guidance.",
    thumbnail:
      "https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&q=80&w=1200",
    duration: "12 months",
    students: "500+",
    subjects: [
      "Accountancy",
      "Business Studies",
      "Economics",
      "Mathematics",
      "English",
    ],
    features: [
      "Expert Faculty",
      "Study Material",
      "Regular Tests",
      "Doubt Sessions",
      "Parent Meetings",
      "Performance Reports",
      "Practice Papers",
      "Career Guidance",
    ],
    onlinePrice: "₹15,000",
    offlinePrice: "₹25,000",
    playlist: "PLNn0hJzC5ok7BVSdh3CXoOBX1aBcbyX2y",
  },
  "class-12-commerce": {
    id: "class-12-commerce",
    title: "Class 12 Commerce",
    description:
      "Complete preparation for Class 12 board exams and competitive exams.",
    thumbnail:
      "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?auto=format&fit=crop&q=80&w=1200",
    duration: "12 months",
    students: "600+",
    subjects: [
      "Accountancy",
      "Business Studies",
      "Economics",
      "Mathematics",
      "English",
    ],
    features: [
      "Board Exam Preparation",
      "Mock Tests",
      "Career Guidance",
      "Performance Analysis",
      "Study Material",
      "Doubt Sessions",
      "Previous Year Papers",
      "Extra Classes",
    ],
    onlinePrice: "₹18,000",
    offlinePrice: "₹28,000",
    playlist: "PLNn0hJzC5ok7BVSdh3CXoOBX1aBcbyX2y",
  },
  "bcom-ccf-sem1": {
    id: "bcom-ccf-sem1",
    title: "B.Com CCF Semester 1",
    description: "Foundation courses in commerce and financial accounting.",
    thumbnail:
      "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&q=80&w=1200",
    duration: "6 months",
    students: "200+",
    subjects: [
      "Financial Accounting",
      "Business Mathematics",
      "Business Communication",
      "Business Economics",
      "Business Environment",
    ],
    features: [
      "Core Subject Coverage",
      "Practical Training",
      "Industry Exposure",
      "Expert Guidance",
      "Study Material",
      "Regular Tests",
      "Doubt Sessions",
      "Library Access",
    ],
    onlinePrice: "₹12,000",
    offlinePrice: "₹20,000",
    playlist: "PLNn0hJzC5ok7BVSdh3CXoOBX1aBcbyX2y",
  },
  "bcom-ccf-sem2": {
    id: "bcom-ccf-sem2",
    title: "B.Com CCF Semester 2",
    description:
      "Advanced concepts in commerce and corporate accounting with practical applications.",
    thumbnail:
      "https://yt3.ggpht.com/R15YXPq2_DczMGVHicrtW2E-ZvSq7qF5GxDOHOW1lcIysQBu94Wz9U_sgU_YOT1td07uccUi5Otlzg=s1600-rw-nd-v1",
    duration: "6 months",
    students: "180+",
    subjects: [
      "Corporate Accounting",
      "Cost Accounting",
      "Business Statistics",
      "Commercial Law",
      "Digital Marketing Basics",
    ],
    features: [
      "Advanced Accounting Concepts",
      "Case Study Analysis",
      "Industry Projects",
      "Expert Guidance",
      "Regular Assessments",
      "Practical Training",
      "Doubt Sessions",
      "Digital Resources",
    ],
    onlinePrice: "₹12,000",
    offlinePrice: "₹20,000",
    playlist: "PLNn0hJzC5ok7BVSdh3CXoOBX1aBcbyX2y",
  },
  "bcom-ccf-sem3": {
    id: "bcom-ccf-sem3",
    title: "B.Com CCF Semester 3",
    description:
      "Specialized courses in corporate finance and taxation with industry exposure.",
    thumbnail:
      "https://yt3.ggpht.com/lgEIT6Ehkqx7SgJMGu4Lrania7nkerSGzmgPwaheq1ih_A1uxbKZPkFirDu4UDhvA3_8xTJUuiu_OQ=s1080-rw-nd-v1",
    duration: "6 months",
    students: "150+",
    subjects: [
      "Advanced Corporate Accounting",
      "Business Taxation",
      "Company Law",
      "Financial Management",
      "E-Commerce",
    ],
    features: [
      "Industry Expert Sessions",
      "Tax Filing Practice",
      "Company Law Cases",
      "Financial Analysis",
      "Live Projects",
      "Mock Interviews",
      "Career Counseling",
      "Industry Visits",
    ],
    onlinePrice: "₹12,000",
    offlinePrice: "₹20,000",
    playlist: "PLNn0hJzC5ok7BVSdh3CXoOBX1aBcbyX2y",
  },
  "bcom-ccf-sem4": {
    id: "bcom-ccf-sem4",
    title: "B.Com CCF Semester 4",
    description:
      "Advanced financial management and business economics with practical training.",
    thumbnail:
      "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&q=80&w=1200",
    duration: "6 months",
    students: "160+",
    subjects: [
      "Advanced Financial Management",
      "Business Economics",
      "Auditing",
      "Information Systems",
      "Business Ethics",
    ],
    features: [
      "Financial Analysis Tools",
      "Economic Case Studies",
      "Audit Practice",
      "Ethics Workshops",
      "Industry Projects",
      "Guest Lectures",
      "Internship Support",
      "Placement Training",
    ],
    onlinePrice: "₹12,000",
    offlinePrice: "₹20,000",
    playlist: "PLNn0hJzC5ok7BVSdh3CXoOBX1aBcbyX2y",
  },
  "bcom-ccf-sem5": {
    id: "bcom-ccf-sem5",
    title: "B.Com CCF Semester 5",
    description:
      "Strategic management and advanced accounting with industry integration.",
    thumbnail:
      "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&q=80&w=1200",
    duration: "6 months",
    students: "140+",
    subjects: [
      "Strategic Management",
      "Advanced Accounting",
      "Corporate Tax Planning",
      "Investment Management",
      "Risk Management",
    ],
    features: [
      "Strategic Planning Workshops",
      "Tax Planning Sessions",
      "Investment Analysis",
      "Risk Assessment",
      "Industry Projects",
      "Career Guidance",
      "Mock Interviews",
      "Placement Support",
    ],
    onlinePrice: "₹12,000",
    offlinePrice: "₹20,000",
    playlist: "PLNn0hJzC5ok7BVSdh3CXoOBX1aBcbyX2y",
  },
  "bcom-ccf-sem6": {
    id: "bcom-ccf-sem6",
    title: "B.Com CCF Semester 6",
    description:
      "Final semester specialization with focus on career preparation.",
    thumbnail:
      "https://yt3.ggpht.com/8A0ugyX82sV2ZhHaiiiHcJaPaPY6cjH-ptbEplup-9M4TLHqqctxYT27JkikMQL-JiN1nMdjuWAPhBQ=s1529-rw-nd-v1",
    duration: "6 months",
    students: "130+",
    subjects: [
      "International Finance",
      "Project Management",
      "Business Analytics",
      "Financial Markets",
      "Professional Ethics",
    ],
    features: [
      "Industry Integration",
      "Project Work",
      "Analytics Training",
      "Market Analysis",
      "Ethics Workshop",
      "Placement Preparation",
      "Industry Visits",
      "Alumni Connect",
    ],
    onlinePrice: "₹12,000",
    offlinePrice: "₹20,000",
    playlist: "PLNn0hJzC5ok7BVSdh3CXoOBX1aBcbyX2y",
  },
  mba: {
    id: "mba",
    title: "MBA",
    description:
      "Comprehensive MBA preparation with focus on practical knowledge and industry exposure.",
    thumbnail:
      "https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&q=80&w=1200",
    duration: "24 months",
    students: "100+",
    subjects: [
      "Management Principles",
      "Financial Management",
      "Marketing Management",
      "Human Resource Management",
      "Operations Management",
      "Strategic Management",
      "Business Analytics",
      "International Business",
    ],
    features: [
      "Industry Expert Sessions",
      "Case Study Analysis",
      "Live Projects",
      "Internship Support",
      "Placement Assistance",
      "Leadership Training",
      "Soft Skills Development",
      "Research Projects",
    ],
    onlinePrice: "₹35,000",
    offlinePrice: "₹45,000",
    playlist: "PLNn0hJzC5ok7BVSdh3CXoOBX1aBcbyX2y",
  },
  bba: {
    id: "bba",
    title: "BBA",
    description:
      "Comprehensive undergraduate business program with practical exposure.",
    thumbnail:
      "https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&q=80&w=1200",
    duration: "36 months",
    students: "120+",
    subjects: [
      "Business Management",
      "Marketing",
      "Finance",
      "Human Resources",
      "Operations",
      "Business Law",
      "Economics",
      "Entrepreneurship",
    ],
    features: [
      "Industry Training",
      "Case Studies",
      "Live Projects",
      "Internships",
      "Soft Skills",
      "Placement Support",
      "Guest Lectures",
      "Industrial Visits",
    ],
    onlinePrice: "₹25,000",
    offlinePrice: "₹35,000",
    playlist: "PLNn0hJzC5ok7BVSdh3CXoOBX1aBcbyX2y",
  },
  "ms-office": {
    id: "ms-office",
    title: "MS Office",
    description:
      "Comprehensive Microsoft Office suite training for professionals.",
    thumbnail:
      "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&q=80&w=1200",
    duration: "3 months",
    students: "200+",
    subjects: [
      "MS Word",
      "MS Excel",
      "MS PowerPoint",
      "MS Access",
      "MS Outlook",
    ],
    features: [
      "Hands-on Training",
      "Real Projects",
      "Certificate",
      "Job Support",
      "Practice Sessions",
      "Assessment Tests",
      "Course Material",
      "Placement Assistance",
    ],
    onlinePrice: "₹8,000",
    offlinePrice: "₹12,000",
    playlist: "PLNn0hJzC5ok7BVSdh3CXoOBX1aBcbyX2y",
  },
  "gst-tally": {
    id: "gst-tally",
    title: "GST/Tally",
    description:
      "Professional training in GST compliance and Tally software with practical exposure.",
    thumbnail:
      "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?auto=format&fit=crop&q=80&w=1200",
    duration: "4 months",
    students: "150+",
    subjects: [
      "GST Fundamentals",
      "Tally Prime",
      "GST Returns",
      "E-Way Bill",
      "Input Tax Credit",
    ],
    features: [
      "Practical Training",
      "Live Projects",
      "GST Portal",
      "Return Filing",
      "Case Studies",
      "Certificate",
      "Job Support",
      "Industry Connect",
    ],
    onlinePrice: "₹10,000",
    offlinePrice: "₹15,000",
    playlist: "PLNn0hJzC5ok7BVSdh3CXoOBX1aBcbyX2y",
  },
  mcom: {
    id: "mcom",
    title: "M.Com",
    description:
      "Advanced studies in commerce with specialization options and research focus.",
    thumbnail:
      "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&q=80&w=1200",
    duration: "24 months",
    students: "80+",
    subjects: [
      "Advanced Accounting",
      "Financial Management",
      "Research Methodology",
      "Business Economics",
      "Corporate Law",
      "Tax Planning",
      "Strategic Management",
      "International Finance",
    ],
    features: [
      "Research Projects",
      "Specialization",
      "Industry Projects",
      "Expert Faculty",
      "Thesis Guidance",
      "Publication Support",
      "Seminar Participation",
      "Career Guidance",
    ],
    onlinePrice: "₹30,000",
    offlinePrice: "₹40,000",
    playlist: "PLNn0hJzC5ok7BVSdh3CXoOBX1aBcbyX2y",
  },
};

export const demoVideos = [
  {
    id: 1,
    title: "Accounting Basics Explained",
    videoId: "D0p9rihk8Xc",
    embedUrl: "https://www.youtube.com/embed/D0p9rihk8Xc?si=81RTi2_1GnBZZ0Cq",
  },
  {
    id: 2,
    title: "Business Studies Introduction",
    videoId: "1UfcE_kUsV8",
    embedUrl: "https://www.youtube.com/embed/1UfcE_kUsV8?si=yu35igWhoaOEmVpx",
  },
  {
    id: 3,
    title: "Economics Fundamentals",
    videoId: "K6deKswjRY8",
    embedUrl: "https://www.youtube.com/embed/K6deKswjRY8?si=ntusyNUwWC03v_H3",
  },
  {
    id: 4,
    title: "Commerce Concepts",
    videoId: "So6_meVqU38",
    embedUrl: "https://www.youtube.com/embed/So6_meVqU38?si=SpD3ckjWKTetoFl1",
  },
  {
    id: 5,
    title: "Business Mathematics",
    videoId: "GmWICBwro5o",
    embedUrl: "https://www.youtube.com/embed/GmWICBwro5o?si=pa6ZDGpP61DybjdE",
  },
];

export const facultyMembers = [
  {
    name: "Aditya Gupta",
    role: "Founder & Lead Instructor",
    subjects: ["Advanced Accountancy", "Business Studies"],
    image:
      "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=400",
  },
  {
    name: "Priya Sharma",
    role: "Senior Faculty",
    subjects: ["Economics", "Business Mathematics"],
    image:
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=400",
  },
  {
    name: "Rajesh Kumar",
    role: "Course Coordinator",
    subjects: ["Cost Accounting", "GST"],
    image:
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=400",
  },
];
